// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectName.Infra.Context;

#nullable disable

namespace ProjectName.Infra.Migrations
{
    [DbContext(typeof(DBCntxt))]
    [Migration("20230528065941_Donor")]
    partial class Donor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApiUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "51552dfa-6d4a-46cf-8086-5de76498b760",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "6e19f0ef-010c-4626-856b-e9fcbc1e404c",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donationz.DonationCategory", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DonationCategorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8518),
                            Description = "DonationCategory 1 Description",
                            Title = "DonationCategory 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8518)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8520),
                            Description = "DonationCategory 2 Description",
                            Title = "DonationCategory 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8521)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8522),
                            Description = "DonationCategory 3 Description",
                            Title = "DonationCategory 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8522)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donationz.DonationCellMaster", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationzId")
                        .HasColumnType("int");

                    b.Property<int>("MajlisId")
                        .HasColumnType("int");

                    b.Property<int>("SUId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationzId");

                    b.HasIndex("MajlisId");

                    b.HasIndex("SUId");

                    b.ToTable("DonationCellMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9270),
                            Description = "DonationCellMaster 1 Description",
                            LocationzId = 1,
                            MajlisId = 1,
                            SUId = 1,
                            Title = "DonationCellMaster 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9270)
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9276),
                            Description = "DonationCellMaster 2 Description",
                            LocationzId = 2,
                            MajlisId = 2,
                            SUId = 2,
                            Title = "DonationCellMaster 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9276)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donationz.DonationSubType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonationTypeId");

                    b.ToTable("DonationSubTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8930),
                            Description = "DonationCellMaster 1 Description",
                            DonationTypeId = 1,
                            Title = "DonationCellMaster 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8931)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8936),
                            Description = "DonationCellMaster 2 Description",
                            DonationTypeId = 2,
                            Title = "DonationCellMaster 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8936)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donationz.DonationType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("COAId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonationCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SysmanAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("COAId");

                    b.HasIndex("DonationCategoryId");

                    b.HasIndex("SysmanAccountId");

                    b.ToTable("DonationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            COAId = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8724),
                            Description = "DonationType 1 Description",
                            DonationCategoryId = 1,
                            SysmanAccountId = 1,
                            Title = "DonationType 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8724)
                        },
                        new
                        {
                            Id = 2,
                            COAId = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8730),
                            Description = "DonationType Description",
                            DonationCategoryId = 2,
                            SysmanAccountId = 2,
                            Title = "DonationType 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8731)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donationz.TargetAssignment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IncreasePercentage")
                        .HasColumnType("int");

                    b.Property<int>("MajlisId")
                        .HasColumnType("int");

                    b.Property<int>("SUId")
                        .HasColumnType("int");

                    b.Property<int>("SystemzId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TargetFor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TargetFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MajlisId");

                    b.HasIndex("SUId");

                    b.HasIndex("SystemzId");

                    b.ToTable("TargetAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9464),
                            Description = "TargetAssignment 1 Description",
                            IncreasePercentage = 20,
                            MajlisId = 1,
                            SUId = 1,
                            SystemzId = 1,
                            TargetFor = new DateTime(2023, 6, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9467),
                            TargetFrom = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9467),
                            Title = "TargetAssignment 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9464)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9475),
                            Description = "TargetAssignment 2 Description",
                            IncreasePercentage = 20,
                            MajlisId = 2,
                            SUId = 2,
                            SystemzId = 2,
                            TargetFor = new DateTime(2023, 6, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9477),
                            TargetFrom = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9477),
                            Title = "TargetAssignment 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9476)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donor.DonorBasic", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DonorTypeId");

                    b.HasIndex("OrgId");

                    b.ToTable("DonorBasics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 203, DateTimeKind.Utc).AddTicks(41),
                            Description = "DonorBasic 1 Description",
                            DonorTypeId = 1,
                            Email = "ahsansoftengineer@gmail.com",
                            Gender = 1,
                            Mobile = "3212827700",
                            OrgId = 1,
                            Title = "DonorBasic 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 203, DateTimeKind.Utc).AddTicks(41)
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 203, DateTimeKind.Utc).AddTicks(48),
                            Description = "DonorBasic 2 Description",
                            DonorTypeId = 2,
                            Email = "asdf@gmail.com",
                            Gender = 0,
                            Mobile = "3212825500",
                            OrgId = 2,
                            Title = "DonorBasic 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 203, DateTimeKind.Utc).AddTicks(48)
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 203, DateTimeKind.Utc).AddTicks(50),
                            Description = "DonorBasic 3 Description",
                            DonorTypeId = 2,
                            Email = "sumaya@gmail.com",
                            Gender = 2,
                            Mobile = "3212826600",
                            OrgId = 2,
                            Title = "DonorBasic 3",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 203, DateTimeKind.Utc).AddTicks(50)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donor.DonorType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DonorTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9828),
                            Description = "DonorType 1 Description",
                            Status = 0,
                            Title = "DonorType 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9829)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9834),
                            Description = "DonorType 2 Description",
                            Status = 1,
                            Title = "DonorType 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9835)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9836),
                            Description = "DonorType 3 Description",
                            Status = 2,
                            Title = "DonorType 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(9837)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Extraz.COA", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("COAs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7406),
                            Description = "COA 1 Description",
                            Title = "COA 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7407)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7410),
                            Description = "COA 2 Description",
                            Title = "COA 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7411)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7412),
                            Description = "COA 3 Description",
                            Title = "COA 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7412)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Extraz.Locationz", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Locationzs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7348),
                            Description = "Locationz 1 Description",
                            Title = "Locationz 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7348)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7352),
                            Description = "Locationz 2 Description",
                            Title = "Locationz 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7353)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7354),
                            Description = "Locationz 3 Description",
                            Title = "Locationz 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7355)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Extraz.Majlis", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Majliss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7381),
                            Description = "Majlis 1 Description",
                            Title = "Majlis 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7382)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7384),
                            Description = "Majlis 2 Description",
                            Title = "Majlis 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7385)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7386),
                            Description = "Majlis 3 Description",
                            Title = "Majlis 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7386)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Extraz.SysmanAccount", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SysmanAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7432),
                            Description = "SysmanAccount 1 Description",
                            Title = "SysmanAccount 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7432)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7465),
                            Description = "SysmanAccount 2 Description",
                            Title = "SysmanAccount 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7465)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7466),
                            Description = "SysmanAccount 3 Description",
                            Title = "SysmanAccount 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7466)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.BG", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BGs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5840),
                            Description = "BG 1 Description",
                            Title = "BG 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5840)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5843),
                            Description = "BG 2 Description",
                            Title = "BG 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5843)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5844),
                            Description = "BG 3 Description",
                            Title = "BG 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5844)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.LE", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("BGId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BGId");

                    b.ToTable("LEs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BGId = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6021),
                            Description = "LE 1 Description",
                            Title = "LE 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6022)
                        },
                        new
                        {
                            Id = 2,
                            BGId = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6026),
                            Description = "LE 2 Description",
                            Title = "LE 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6026)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.OU", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deposit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LEId")
                        .HasColumnType("int");

                    b.Property<string>("Law")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarningImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarningImg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LEId");

                    b.ToTable("OUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6208),
                            Description = "OU 1 Description",
                            LEId = 1,
                            Title = "OU 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6208)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6212),
                            Description = "OU 2 Description",
                            LEId = 2,
                            Title = "OU 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6213)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.Org", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orgs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5592),
                            Description = "Org 1 Description",
                            Title = "Org 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5595)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5603),
                            Description = "Org 2 Description",
                            Title = "Org 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5604)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5605),
                            Description = "Org 3 Description",
                            Title = "Org 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5606)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.SU", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OUId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OUId");

                    b.ToTable("SUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6398),
                            Description = "SU 1 Description",
                            OUId = 1,
                            Title = "SU 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6398)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6403),
                            Description = "SU 2 Description",
                            OUId = 2,
                            Title = "SU 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(6403)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.Systemz", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("Systemzs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5802),
                            Description = "SU 1 Description",
                            OrgId = 1,
                            Title = "SU 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5802)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5806),
                            Description = "SU 2 Description",
                            OrgId = 2,
                            Title = "SU 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(5807)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.MadaniBastaEntity.MadaniBasta", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MadaniBastas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8088),
                            Description = "MadaniBasta 1 Description",
                            Title = "MadaniBasta 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8088)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8092),
                            Description = "MadaniBasta 2 Description",
                            Title = "MadaniBasta 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8092)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8093),
                            Description = "MadaniBasta 3 Description",
                            Title = "MadaniBasta 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8094)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.MadaniBastaEntity.MadaniBastaEvent", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MadaniBastaEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8120),
                            Description = "MadaniBastaEvent 1 Description",
                            Title = "MadaniBastaEvent 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8121)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8126),
                            Description = "MadaniBastaEvent 2 Description",
                            Title = "MadaniBastaEvent 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8126)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8127),
                            Description = "MadaniBastaEvent 3 Description",
                            Title = "MadaniBastaEvent 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8127)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.MadaniBastaEntity.MadaniBastaPlace", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MadaniBastaPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8145),
                            Description = "MadaniBastaPlace 1 Description",
                            Title = "MadaniBastaPlace 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8145)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8147),
                            Description = "MadaniBastaPlace 2 Description",
                            Title = "MadaniBastaPlace 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8148)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8149),
                            Description = "MadaniBastaPlace 3 Description",
                            Title = "MadaniBastaPlace 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8149)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.MadaniBastaEntity.MadaniBastaSubCategory", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MadaniBastaId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MadaniBastaId");

                    b.ToTable("MadaniBastaSubCategorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8324),
                            Description = "MadaniBastaSubCategory 1 Description",
                            MadaniBastaId = 1,
                            Title = "MadaniBastaSubCategory 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8325)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8329),
                            Description = "MadaniBastaSubCategory 2 Description",
                            MadaniBastaId = 2,
                            Title = "MadaniBastaSubCategory 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8329)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Regionz.City", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Citys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8050),
                            Description = "SU 1 Description",
                            StateId = 1,
                            Title = "SU 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8051)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8054),
                            Description = "SU 2 Description",
                            StateId = 2,
                            Title = "SU 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(8055)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Regionz.Country", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7488),
                            Description = "Country 1 Description",
                            Title = "Country 1 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7488)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7491),
                            Description = "Country 2 Description",
                            Title = "Country 2 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7491)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7492),
                            Description = "Country 3 Description",
                            Title = "Country 3 Title",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7492)
                        });
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Regionz.State", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7841),
                            Description = "SU 1 Description",
                            Title = "SU 1",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7841)
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            CreatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7846),
                            Description = "SU 2 Description",
                            Title = "SU 2",
                            UpdatedAt = new DateTime(2023, 5, 28, 6, 59, 41, 202, DateTimeKind.Utc).AddTicks(7847)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.ApiUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("ApiUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Infra.Entity.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donationz.DonationCellMaster", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Extraz.Locationz", "Locationz")
                        .WithMany()
                        .HasForeignKey("LocationzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Infra.Entity.Extraz.Majlis", "Majlis")
                        .WithMany()
                        .HasForeignKey("MajlisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Infra.Entity.Hierarchy.SU", "SU")
                        .WithMany()
                        .HasForeignKey("SUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locationz");

                    b.Navigation("Majlis");

                    b.Navigation("SU");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donationz.DonationSubType", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Donationz.DonationType", "DonationType")
                        .WithMany()
                        .HasForeignKey("DonationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonationType");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donationz.DonationType", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Extraz.COA", "COA")
                        .WithMany()
                        .HasForeignKey("COAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Infra.Entity.Donationz.DonationCategory", "DonationCategory")
                        .WithMany()
                        .HasForeignKey("DonationCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Infra.Entity.Extraz.SysmanAccount", "SysmanAccount")
                        .WithMany()
                        .HasForeignKey("SysmanAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("COA");

                    b.Navigation("DonationCategory");

                    b.Navigation("SysmanAccount");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donationz.TargetAssignment", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Extraz.Majlis", "Majlis")
                        .WithMany()
                        .HasForeignKey("MajlisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Infra.Entity.Hierarchy.SU", "SU")
                        .WithMany()
                        .HasForeignKey("SUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Infra.Entity.Hierarchy.Systemz", "Systemz")
                        .WithMany()
                        .HasForeignKey("SystemzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Majlis");

                    b.Navigation("SU");

                    b.Navigation("Systemz");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donor.DonorBasic", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Regionz.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Infra.Entity.Donor.DonorType", "DonorType")
                        .WithMany("DonorBasics")
                        .HasForeignKey("DonorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Infra.Entity.Hierarchy.Org", "Org")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("DonorType");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.LE", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Hierarchy.BG", "BG")
                        .WithMany("LEs")
                        .HasForeignKey("BGId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BG");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.OU", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Hierarchy.LE", "LE")
                        .WithMany()
                        .HasForeignKey("LEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LE");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.SU", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Hierarchy.OU", "OU")
                        .WithMany()
                        .HasForeignKey("OUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OU");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.Systemz", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Hierarchy.Org", "Org")
                        .WithMany("Systemzs")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Org");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.MadaniBastaEntity.MadaniBastaSubCategory", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.MadaniBastaEntity.MadaniBasta", "MadaniBasta")
                        .WithMany("MadaniBastaSubCategorys")
                        .HasForeignKey("MadaniBastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MadaniBasta");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Regionz.City", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Regionz.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Regionz.State", b =>
                {
                    b.HasOne("ProjectName.Infra.Entity.Regionz.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.ApiUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Donor.DonorType", b =>
                {
                    b.Navigation("DonorBasics");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.BG", b =>
                {
                    b.Navigation("LEs");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.Hierarchy.Org", b =>
                {
                    b.Navigation("Systemzs");
                });

            modelBuilder.Entity("ProjectName.Infra.Entity.MadaniBastaEntity.MadaniBasta", b =>
                {
                    b.Navigation("MadaniBastaSubCategorys");
                });
#pragma warning restore 612, 618
        }
    }
}
